from PyQt5 import QtCore, QtGui, QtWidgets
import qrcode
import qrcode.image.svg
import os

link = []
path = []


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.StartWindow = MainWindow
        self.StartWindow.setObjectName("StartWindow")
        self.StartWindow.resize(794, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("QFrame {\n"
                                 "background-color: white;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(280, 40, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.pushButtonPng = QtWidgets.QPushButton(self.frame)
        self.pushButtonPng.setGeometry(QtCore.QRect(100, 400, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(16)
        self.pushButtonPng.setFont(font)
        self.pushButtonPng.setStyleSheet("QPushButton {\n"
                                         "border-radius: 5px;\n"
                                         "background-color: rgb(83,104,114);\n"
                                         "color: white;\n"
                                         "}")
        self.pushButtonPng.setObjectName("pushButtonPng")
        self.select_label = QtWidgets.QLabel(self.frame)
        self.select_label.setGeometry(QtCore.QRect(280, 320, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.select_label.setFont(font)
        self.select_label.setAlignment(QtCore.Qt.AlignCenter)
        self.select_label.setObjectName("select_label")
        self.description = QtWidgets.QLabel(self.frame)
        self.description.setGeometry(QtCore.QRect(190, 120, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setScaledContents(False)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.description.setObjectName("description")
        self.pushButtonSvg = QtWidgets.QPushButton(self.frame)
        self.pushButtonSvg.setGeometry(QtCore.QRect(460, 400, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(16)
        self.pushButtonSvg.setFont(font)
        self.pushButtonSvg.setStyleSheet("QPushButton {\n"
                                         "border-radius: 5px;\n"
                                         "background-color: rgb(83,104,114);\n"
                                         "color: white;\n"
                                         "}")
        self.pushButtonSvg.setObjectName("pushButtonSvg")
        self.ratataololo = QtWidgets.QLabel(self.frame)
        self.ratataololo.setGeometry(QtCore.QRect(330, 490, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ratataololo.setFont(font)
        self.ratataololo.setScaledContents(False)
        self.ratataololo.setAlignment(QtCore.Qt.AlignCenter)
        self.ratataololo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ratataololo.setObjectName("ratataololo")
        self.insert_link_field = QtWidgets.QLineEdit(self.frame)
        self.insert_link_field.setGeometry(QtCore.QRect(140, 270, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.insert_link_field.setFont(font)
        self.insert_link_field.setStyleSheet("QLineEdit {\n"
                                             "border-radius: 5px;\n"
                                             "border: 2px solid gray;\n"
                                             "}")
        self.insert_link_field.setText("")
        self.insert_link_field.setObjectName("insert_link_field")
        self.link_label = QtWidgets.QLabel(self.frame)
        self.link_label.setGeometry(QtCore.QRect(300, 210, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.link_label.setFont(font)
        self.link_label.setAlignment(QtCore.Qt.AlignCenter)
        self.link_label.setObjectName("link_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButtonPng.clicked.connect(self.png)
        self.pushButtonSvg.clicked.connect(self.svg)

    def svg(self):
        self.link = self.insert_link_field.text()
        if self.link:
            fileName, _ = QtWidgets.QFileDialog.getSaveFileName(self.StartWindow, "Change path to save your file", 'qr',
                                                                "*.svg")
            path.append(fileName)
            factory = qrcode.image.svg.SvgPathImage
            img = qrcode.make(self.link, image_factory=factory)
            img.save(fileName)
            if fileName:
                self.ReadyWindow = QtWidgets.QMainWindow()
                self.ready_ui = Ui_ReadyWindow()
                self.ready_ui.setupUi(self.ReadyWindow)
                self.StartWindow.close()
                self.ReadyWindow.show()
            else:
                QtWidgets.QMessageBox.critical(self.StartWindow, "Error", "Incorrect data!")
        else:
            QtWidgets.QMessageBox.critical(self.StartWindow, "Error", "Insert yout link!")

    def png(self):
        self.link = self.insert_link_field.text()
        if self.link:
            link.append(self.link)
            self.PngWindow = QtWidgets.QMainWindow()
            self.png_ui = Ui_PNG()
            self.png_ui.setupUi(self.PngWindow)
            self.StartWindow.close()
            self.PngWindow.show()
        else:
            QtWidgets.QMessageBox.critical(self.StartWindow, "Error", "Insert yout link!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "QR-maker"))
        self.pushButtonPng.setText(_translate("MainWindow", "PNG"))
        self.select_label.setText(_translate("MainWindow", "Select format:"))
        self.description.setText(_translate("MainWindow", "This program can generate qr-code with your text\n"
                                                          " in PNG in different colors and sizes and SVG."))
        self.pushButtonSvg.setText(_translate("MainWindow", "SVG"))
        self.ratataololo.setText(_translate("MainWindow", "by ratataololo"))
        self.link_label.setText(_translate("MainWindow", "Insert your link here:"))


class Ui_PNG(object):
    def setupUi(self, MainWindow):
        self.pngwindow = MainWindow
        self.pngwindow.setObjectName("MainWindow")
        self.pngwindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("QFrame {\n"
                                 "background-color: white;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(320, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.bg_color_label = QtWidgets.QLabel(self.frame)
        self.bg_color_label.setGeometry(QtCore.QRect(40, 120, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label.setFont(font)
        self.bg_color_label.setScaledContents(False)
        self.bg_color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label.setObjectName("bg_color_label")
        self.bgcolor_R = QtWidgets.QLineEdit(self.frame)
        self.bgcolor_R.setGeometry(QtCore.QRect(230, 150, 41, 21))
        self.bgcolor_R.setStyleSheet("QLineEdit {\n"
                                     "border-radius: 5px;\n"
                                     "border: 2px solid gray;\n"
                                     "}")
        self.bgcolor_R.setObjectName("bgcolor_R")
        rx = QtCore.QRegExp('1[0-9][0-9]|25[0-5]|[0-9][0-9]|2[0-4][0-9]')
        val = QtGui.QRegExpValidator(rx)
        self.bgcolor_R.setValidator(val)
        self.qr_color_label = QtWidgets.QLabel(self.frame)
        self.qr_color_label.setGeometry(QtCore.QRect(40, 220, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.qr_color_label.setFont(font)
        self.qr_color_label.setScaledContents(False)
        self.qr_color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_color_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.qr_color_label.setObjectName("qr_color_label")
        self.size_list = QtWidgets.QComboBox(self.frame)
        self.size_list.setGeometry(QtCore.QRect(110, 430, 151, 31))
        self.size_list.setStyleSheet("QComboBox {\n"
                                     "border-radius: 5px;\n"
                                     "border: 2px solid gray;\n"
                                     "padding:8px;\n"
                                     "}")
        self.size_list.setObjectName("size_list")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_list.addItem("")
        self.size_label = QtWidgets.QLabel(self.frame)
        self.size_label.setGeometry(QtCore.QRect(100, 370, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.size_label.setFont(font)
        self.size_label.setStyleSheet("background-color: None;")
        self.size_label.setScaledContents(False)
        self.size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.size_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.size_label.setObjectName("size_label")
        self.closeness_label = QtWidgets.QLabel(self.frame)
        self.closeness_label.setGeometry(QtCore.QRect(530, 370, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.closeness_label.setFont(font)
        self.closeness_label.setStyleSheet("background-color: None;")
        self.closeness_label.setScaledContents(False)
        self.closeness_label.setAlignment(QtCore.Qt.AlignCenter)
        self.closeness_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.closeness_label.setObjectName("closeness_label")
        self.closeness_list = QtWidgets.QComboBox(self.frame)
        self.closeness_list.setGeometry(QtCore.QRect(540, 430, 151, 31))
        self.closeness_list.setStyleSheet("QComboBox {\n"
                                          "border-radius: 5px;\n"
                                          "border: 2px solid gray;\n"
                                          "padding:8px;\n"
                                          "}")
        self.closeness_list.setObjectName("closeness_list")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.closeness_list.addItem("")
        self.border_size_label = QtWidgets.QLabel(self.frame)
        self.border_size_label.setGeometry(QtCore.QRect(320, 370, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.border_size_label.setFont(font)
        self.border_size_label.setStyleSheet("background-color: None;")
        self.border_size_label.setScaledContents(False)
        self.border_size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.border_size_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.border_size_label.setObjectName("border_size_label")
        self.border_size_list = QtWidgets.QComboBox(self.frame)
        self.border_size_list.setGeometry(QtCore.QRect(330, 430, 151, 31))
        self.border_size_list.setStyleSheet("QComboBox {\n"
                                            "border-radius: 5px;\n"
                                            "border: 2px solid gray;\n"
                                            "padding:8px;\n"
                                            "}")
        self.border_size_list.setObjectName("border_size_list")
        self.border_size_list.addItem("")
        self.border_size_list.addItem("")
        self.border_size_list.addItem("")
        self.border_size_list.addItem("")
        self.border_size_list.addItem("")
        self.border_size_list.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(460, 110, 30, 30))
        self.frame_2.setStyleSheet("background-color: rgb(235,76,66);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(460, 150, 30, 30))
        self.frame_3.setStyleSheet("background-color: rgb(244,202,22);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(460, 230, 30, 30))
        self.frame_5.setStyleSheet("background-color: rgb(49,140,231);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(460, 190, 30, 30))
        self.frame_7.setStyleSheet("background-color: rgb(255,255,255);border: 2px solid gray;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(460, 270, 30, 30))
        self.frame_8.setStyleSheet("background-color: rgb(0,0,0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(510, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(510, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(510, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(510, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(510, 270, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(690, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(640, 110, 30, 30))
        self.frame_9.setStyleSheet("background-color: rgb(32,178,170);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(690, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(690, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(640, 270, 30, 30))
        self.frame_10.setStyleSheet("background-color: rgb(40,88,156);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(640, 190, 30, 30))
        self.frame_13.setStyleSheet("background-color: rgb(204,57,123);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setGeometry(QtCore.QRect(640, 150, 30, 30))
        self.frame_14.setStyleSheet("background-color: rgb(240,116,39);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(690, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setGeometry(QtCore.QRect(640, 230, 30, 30))
        self.frame_15.setStyleSheet("background-color: rgb(127,255,0);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(690, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.sample_label = QtWidgets.QLabel(self.frame)
        self.sample_label.setGeometry(QtCore.QRect(540, 50, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sample_label.setFont(font)
        self.sample_label.setStyleSheet("background-color: None;")
        self.sample_label.setScaledContents(False)
        self.sample_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sample_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sample_label.setObjectName("sample_label")
        self.createButton = QtWidgets.QPushButton(self.frame)
        self.createButton.setGeometry(QtCore.QRect(310, 490, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(16)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("border-radius: 5px; background-color: rgb(32,178,170); color: white;")
        self.createButton.setObjectName("createButton")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(20, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("border-radius:25%; background-color: rgb(32,178,170); color: white;")
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(20, 20))
        self.backButton.setObjectName("backButton")
        self.bg_color_label_2 = QtWidgets.QLabel(self.frame)
        self.bg_color_label_2.setGeometry(QtCore.QRect(210, 150, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label_2.setFont(font)
        self.bg_color_label_2.setStyleSheet("background-color: None;")
        self.bg_color_label_2.setScaledContents(False)
        self.bg_color_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label_2.setObjectName("bg_color_label_2")
        self.bg_color_label_3 = QtWidgets.QLabel(self.frame)
        self.bg_color_label_3.setGeometry(QtCore.QRect(280, 150, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label_3.setFont(font)
        self.bg_color_label_3.setStyleSheet("background-color: None;")
        self.bg_color_label_3.setScaledContents(False)
        self.bg_color_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label_3.setObjectName("bg_color_label_3")
        self.bgcolor_G = QtWidgets.QLineEdit(self.frame)
        self.bgcolor_G.setGeometry(QtCore.QRect(300, 150, 41, 21))
        self.bgcolor_G.setStyleSheet("QLineEdit {\n"
                                     "border-radius: 5px;\n"
                                     "border: 2px solid gray;\n"
                                     "}")
        self.bgcolor_G.setObjectName("bgcolor_G")
        rx = QtCore.QRegExp('1[0-9][0-9]|25[0-5]|[0-9][0-9]|2[0-4][0-9]')
        val = QtGui.QRegExpValidator(rx)
        self.bgcolor_G.setValidator(val)
        self.bg_color_label_4 = QtWidgets.QLabel(self.frame)
        self.bg_color_label_4.setGeometry(QtCore.QRect(350, 150, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label_4.setFont(font)
        self.bg_color_label_4.setStyleSheet("background-color: None;")
        self.bg_color_label_4.setScaledContents(False)
        self.bg_color_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label_4.setObjectName("bg_color_label_4")
        self.bgcolor_B = QtWidgets.QLineEdit(self.frame)
        self.bgcolor_B.setGeometry(QtCore.QRect(370, 150, 41, 21))
        self.bgcolor_B.setStyleSheet("QLineEdit {\n"
                                     "border-radius: 5px;\n"
                                     "border: 2px solid gray;\n"
                                     "}")
        self.bgcolor_B.setObjectName("bgcolor_B")
        rx = QtCore.QRegExp('1[0-9][0-9]|25[0-5]|[0-9][0-9]|2[0-4][0-9]')
        val = QtGui.QRegExpValidator(rx)
        self.bgcolor_B.setValidator(val)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(440, 70, 351, 261))
        self.frame_4.setStyleSheet("border: 2px solid gray; border-radius: 5px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.bg_color_label_5 = QtWidgets.QLabel(self.frame)
        self.bg_color_label_5.setGeometry(QtCore.QRect(350, 250, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label_5.setFont(font)
        self.bg_color_label_5.setStyleSheet("background-color: None;")
        self.bg_color_label_5.setScaledContents(False)
        self.bg_color_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label_5.setObjectName("bg_color_label_5")
        self.fillcolor_R = QtWidgets.QLineEdit(self.frame)
        self.fillcolor_R.setGeometry(QtCore.QRect(230, 250, 41, 21))
        self.fillcolor_R.setStyleSheet("QLineEdit {\n"
                                       "border-radius: 5px;\n"
                                       "border: 2px solid gray;\n"
                                       "}")
        self.fillcolor_R.setObjectName("fillcolor_R")
        rx = QtCore.QRegExp('1[0-9][0-9]|25[0-5]|[0-9][0-9]|2[0-4][0-9]')
        val = QtGui.QRegExpValidator(rx)
        self.fillcolor_R.setValidator(val)
        self.fillcolor_B = QtWidgets.QLineEdit(self.frame)
        self.fillcolor_B.setGeometry(QtCore.QRect(370, 250, 41, 21))
        self.fillcolor_B.setStyleSheet("QLineEdit {\n"
                                       "border-radius: 5px;\n"
                                       "border: 2px solid gray;\n"
                                       "}")
        self.fillcolor_B.setObjectName("fillcolor_B")
        rx = QtCore.QRegExp('1[0-9][0-9]|25[0-5]|[0-9][0-9]|2[0-4][0-9]')
        val = QtGui.QRegExpValidator(rx)
        self.fillcolor_B.setValidator(val)
        self.bg_color_label_6 = QtWidgets.QLabel(self.frame)
        self.bg_color_label_6.setGeometry(QtCore.QRect(210, 250, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label_6.setFont(font)
        self.bg_color_label_6.setStyleSheet("background-color: None;")
        self.bg_color_label_6.setScaledContents(False)
        self.bg_color_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label_6.setObjectName("bg_color_label_6")
        self.bg_color_label_7 = QtWidgets.QLabel(self.frame)
        self.bg_color_label_7.setGeometry(QtCore.QRect(280, 250, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bg_color_label_7.setFont(font)
        self.bg_color_label_7.setStyleSheet("background-color: None;")
        self.bg_color_label_7.setScaledContents(False)
        self.bg_color_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_color_label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bg_color_label_7.setObjectName("bg_color_label_7")
        self.fillcolor_G = QtWidgets.QLineEdit(self.frame)
        self.fillcolor_G.setGeometry(QtCore.QRect(300, 250, 41, 21))
        self.fillcolor_G.setStyleSheet("QLineEdit {\n"
                                       "border-radius: 5px;\n"
                                       "border: 2px solid gray;\n"
                                       "}")
        self.fillcolor_G.setObjectName("fillcolor_G")
        rx = QtCore.QRegExp('1[0-9][0-9]|25[0-5]|[0-9][0-9]|2[0-4][0-9]')
        val = QtGui.QRegExpValidator(rx)
        self.fillcolor_G.setValidator(val)
        self.frame_4.raise_()
        self.logo.raise_()
        self.bg_color_label.raise_()
        self.bgcolor_R.raise_()
        self.qr_color_label.raise_()
        self.size_list.raise_()
        self.size_label.raise_()
        self.closeness_label.raise_()
        self.closeness_list.raise_()
        self.border_size_label.raise_()
        self.border_size_list.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_5.raise_()
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.frame_9.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.frame_10.raise_()
        self.frame_13.raise_()
        self.frame_14.raise_()
        self.label_19.raise_()
        self.frame_15.raise_()
        self.label_20.raise_()
        self.sample_label.raise_()
        self.createButton.raise_()
        self.backButton.raise_()
        self.bg_color_label_2.raise_()
        self.bg_color_label_3.raise_()
        self.bgcolor_G.raise_()
        self.bg_color_label_4.raise_()
        self.bgcolor_B.raise_()
        self.bg_color_label_5.raise_()
        self.fillcolor_R.raise_()
        self.fillcolor_B.raise_()
        self.bg_color_label_6.raise_()
        self.bg_color_label_7.raise_()
        self.fillcolor_G.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.backButton.clicked.connect(self.back_to_main)
        self.createButton.clicked.connect(self.create_qr)
        self.dialogwidget = QtWidgets.QWidget(MainWindow)
        self.dialogwidget.setObjectName("Error")

    def back_to_main(self):
        self.StartWindow = QtWidgets.QMainWindow()
        self.start_ui = Ui_MainWindow()
        self.start_ui.setupUi(self.StartWindow)
        self.StartWindow.show()
        self.pngwindow.close()
        link = []

    def create_qr(self):
        try:
            bg_color = [int(self.bgcolor_R.text()), int(self.bgcolor_G.text()), int(self.bgcolor_B.text())]
            fill_color = [int(self.fillcolor_R.text()), int(self.fillcolor_G.text()), int(self.fillcolor_B.text())]
            bg_color = tuple(bg_color)
            fill_color = tuple(fill_color)
            size = int(self.size_list.currentText()) / 21
            border = int(self.border_size_list.currentText()) / 10
            closeness = self.closeness_list.currentText()
            qr = qrcode.QRCode(
                version=closeness,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=size,
                border=border,
            )
            r = qr.add_data(link[-1])
            qr.make(fit=True)
            img = qr.make_image(back_color=bg_color, fill_color=fill_color)
            fileName, _ = QtWidgets.QFileDialog.getSaveFileName(self.pngwindow, "Change path to save your file", 'qr',
                                                                "*.png")
            if fileName:
                try:
                    path.append(fileName)
                    img.save(fileName)
                    self.ReadyWindow = QtWidgets.QMainWindow()
                    self.ready_ui = Ui_ReadyWindow()
                    self.ready_ui.setupUi(self.ReadyWindow)
                    self.ReadyWindow.show()
                    self.pngwindow.close()
                except:
                    QtWidgets.QMessageBox.critical(self.dialogwidget, "Error", "Incorrect data!")
        except:
            QtWidgets.QMessageBox.critical(self.dialogwidget, "Error", "Incorrect data!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "QR-maker"))
        self.bg_color_label.setText(_translate("MainWindow", "Insert background\n"
                                                             "color in RGB-format\':"))
        self.qr_color_label.setText(_translate("MainWindow", "Insert qr\n"
                                                             "color in RGB-format\':"))
        self.size_list.setItemText(0, _translate("MainWindow", "210"))
        self.size_list.setItemText(1, _translate("MainWindow", "420"))
        self.size_list.setItemText(2, _translate("MainWindow", "630"))
        self.size_list.setItemText(3, _translate("MainWindow", "840"))
        self.size_list.setItemText(4, _translate("MainWindow", "1050"))
        self.size_list.setItemText(5, _translate("MainWindow", "1260"))
        self.size_list.setItemText(6, _translate("MainWindow", "1470"))
        self.size_list.setItemText(7, _translate("MainWindow", "1680"))
        self.size_list.setItemText(8, _translate("MainWindow", "1890"))
        self.size_label.setText(_translate("MainWindow", "Select size in px:"))
        self.closeness_label.setText(_translate("MainWindow", "Select closeness \n (size will be increase):"))
        self.closeness_list.setItemText(0, _translate("MainWindow", "1"))
        self.closeness_list.setItemText(1, _translate("MainWindow", "5"))
        self.closeness_list.setItemText(2, _translate("MainWindow", "10"))
        self.closeness_list.setItemText(3, _translate("MainWindow", "15"))
        self.closeness_list.setItemText(4, _translate("MainWindow", "20"))
        self.closeness_list.setItemText(5, _translate("MainWindow", "25"))
        self.closeness_list.setItemText(6, _translate("MainWindow", "30"))
        self.closeness_list.setItemText(7, _translate("MainWindow", "35"))
        self.closeness_list.setItemText(8, _translate("MainWindow", "40"))
        self.border_size_label.setText(_translate("MainWindow", "Select border size\n"
                                                                " in px:"))
        self.border_size_list.setItemText(0, _translate("MainWindow", "0"))
        self.border_size_list.setItemText(1, _translate("MainWindow", "10"))
        self.border_size_list.setItemText(2, _translate("MainWindow", "20"))
        self.border_size_list.setItemText(3, _translate("MainWindow", "30"))
        self.border_size_list.setItemText(4, _translate("MainWindow", "40"))
        self.border_size_list.setItemText(5, _translate("MainWindow", "50"))
        self.label_2.setText(_translate("MainWindow", "235,76,66"))
        self.label_3.setText(_translate("MainWindow", "244,202,22"))
        self.label_10.setText(_translate("MainWindow", "49,140,231"))
        self.label_12.setText(_translate("MainWindow", "255, 255, 255"))
        self.label_13.setText(_translate("MainWindow", "0, 0, 0"))
        self.label_15.setText(_translate("MainWindow", "40,88,156"))
        self.label_16.setText(_translate("MainWindow", "32,178,170"))
        self.label_18.setText(_translate("MainWindow", "240,116,39"))
        self.label_19.setText(_translate("MainWindow", "127,255,0"))
        self.label_20.setText(_translate("MainWindow", "204,57,123"))
        self.sample_label.setText(_translate("MainWindow", "Some samples:"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.bg_color_label_2.setText(_translate("MainWindow", "R:"))
        self.bg_color_label_3.setText(_translate("MainWindow", "G:"))
        self.bg_color_label_4.setText(_translate("MainWindow", "B:"))
        self.bg_color_label_5.setText(_translate("MainWindow", "B:"))
        self.bg_color_label_6.setText(_translate("MainWindow", "R:"))
        self.bg_color_label_7.setText(_translate("MainWindow", "G:"))


class Ui_ReadyWindow(object):
    def setupUi(self, MainWindow):
        self.ReadyWindow = MainWindow
        self.ReadyWindow.setObjectName("MainWindow")
        self.ReadyWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("QFrame {\n"
                                 "background-color: white;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(330, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.createButton = QtWidgets.QPushButton(self.frame)
        self.createButton.setGeometry(QtCore.QRect(280, 450, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Cyrillic")
        font.setPointSize(16)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("QPushButton {\n"
                                        "border-radius: 5px;\n"
                                        "background-color: rgb(83,104,114);\n"
                                        "color: white;\n"
                                        "}")
        self.createButton.setObjectName("createButton")
        self.description = QtWidgets.QLabel(self.frame)
        self.description.setGeometry(QtCore.QRect(50, 200, 701, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setStyleSheet("color: rgb(32,178,170);")
        self.description.setScaledContents(False)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.description.setObjectName("description")
        self.description_2 = QtWidgets.QLabel(self.frame)
        self.description_2.setGeometry(QtCore.QRect(110, 350, 581, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.description_2.setFont(font)
        self.description_2.setScaledContents(False)
        self.description_2.setAlignment(QtCore.Qt.AlignCenter)
        self.description_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.description_2.setObjectName("description_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.createButton.clicked.connect(self.back_to_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def back_to_main(self):
        self.StartWindow = QtWidgets.QMainWindow()
        self.start_ui = Ui_MainWindow()
        self.start_ui.setupUi(self.StartWindow)
        self.StartWindow.show()
        self.ReadyWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "QR-maker"))
        self.createButton.setText(_translate("MainWindow", "To start window"))
        self.description.setText(
            _translate("MainWindow", "Your file was created and saved in \n {0}!".format(path[-1])))
        self.description_2.setText(_translate("MainWindow", "Click \"To start window\" to create another file"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
